[pytest]
python_files = test_*.py
python_classes = Test*

markers =
    ui: UI tests marker
    smoke: Smoke tests marker
    slow: Slow tests marker
    critical: Critical tests marker
    registration: Registration tests marker
    authorization: Authorization tests marker
    courses: для тестов, связанных с курсами.
    regression: для регрессионных тестов.