[pytest]
python_files = test_*.py
python_classes = Test*

markers =
    ui: UI tests marker
    smoke: Smoke tests marker
    regression: Regression tests marker
    slow: Slow tests marker
    critical: Critical tests marker
    registration: Registration tests marker
    authorization: Authorization tests marker